name: Grab latest SEC FTD Data

on:
  schedule:
    - cron: "0 0 * * 1,2,3,4,5"  # At 12:00am on Monday, Tuesday, Wednesday, Thursday, and Friday
  workflow_dispatch: # Manually trigger the workflow

jobs:
  scrape_and_download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install python dependencies
        run: pip install beautifulsoup4 requests pyodbc pandas
        
      - name: Install ODBC 18 Driver
        run: sudo ACCEPT_EULA=Y apt-get install msodbcsql18 -y
        
      - name: Scrape SEC Site, Parse, and Insert into Azure SQL DB
        env:
          SQL_PASSWORD: ${{ secrets.SQLPW }}
          SQL_UID: ${{ secrets.SQLUID }}
          SQL_SERVER:  ${{ secrets.SQLSERVER }}
        working-directory: ./
        run: | 
          python ./SEC-FTDS-scraper/sec-ftds-scraper.py
          git config user.name github-actions
          git config user.email Iaintgivingyouthis@gmail.com
          git commit -am "Updated File Hash" || echo "There is nothing to commit"
          git push
